const assert=require('assert');const fs=require('fs');const os=require('os');const path=require('path');const {LocalStorage}=require('../lib/storage');const {HueAdapter}=require('../lib/hue');const {Diagnostics}=require('../lib/diagnostics');const {ReconnectController}=require('../lib/reconnect');
const {validateCapabilities}=require('../lib/capabilities');const {migrateLegacyDevice,publicDevice}=require('../lib/device-model');const {DeviceRegistry}=require('../lib/device-registry');const {SimulationAdapter}=require('../lib/simulation');
const {createBackup,validateBackup}=require('../lib/backup');
const demo=[{id:'hue-1',hueId:'1',integration:'hue',type:'light',name:'Testlicht',online:true,on:false,brightness:50}];
async function adapter(fault=''){process.env.HUE_MODE='simulation';process.env.HUE_SIM_FAULT=fault;const dir=fs.mkdtempSync(path.join(os.tmpdir(),'systemone-test-'));const storage=new LocalStorage(dir);return {hue:new HueAdapter({storage,demoDevices:demo,diagnostics:new Diagnostics()}),dir}}
(async()=>{let passed=0;async function test(name,fn){try{await fn();passed++;console.log(`✓ ${name}`)}catch(e){console.error(`✗ ${name}: ${e.message}`);process.exitCode=1}}
await test('Simulation spricht keine echte Bridge an',async()=>{const {hue}=await adapter();assert.equal(hue.mode,'simulation');const b=await hue.discover();assert.equal(b.ip,'127.0.0.1')});
await test('Bridge nicht gefunden',async()=>{const {hue}=await adapter('not-found');assert.equal(await hue.discover(),null)});
await test('Link-Button-Fehler',async()=>{const {hue}=await adapter('link-button');await hue.discover();await assert.rejects(()=>hue.pair(),e=>e.code==='HUE_LINK_BUTTON_REQUIRED')});
await test('Timeout-Fehler',async()=>{const {hue}=await adapter('timeout');await hue.discover();await hue.pair();await assert.rejects(()=>hue.fetchLights(),e=>e.code==='HUE_TIMEOUT')});
await test('Auth-Fehler',async()=>{const {hue}=await adapter('auth');await hue.discover();await hue.pair();await assert.rejects(()=>hue.fetchLights(),e=>e.code==='HUE_AUTH_ERROR')});
await test('Offline-Gerät',async()=>{const {hue}=await adapter('offline');await hue.discover();await hue.pair();const lights=await hue.fetchLights();assert.equal(lights[0].online,false)});
await test('Befehlsfehler',async()=>{const {hue}=await adapter('command');await hue.discover();await hue.pair();await assert.rejects(()=>hue.setLight(demo[0],{on:true}),e=>e.code==='HUE_COMMAND_FAILED')});
await test('Persistenz schreibt und liest Zustand',async()=>{const {dir}=await adapter();const s=new LocalStorage(dir);s.saveState({ok:true});assert.equal(s.loadState({}).ok,true)});
await test('Reconnect wechselt nach Fehler in Backoff',async()=>{const r=new ReconnectController({minDelayMs:1,maxDelayMs:2});r.failure({code:'HUE_TIMEOUT'});assert.equal(r.state,'backoff');assert.equal(r.attempt,1);assert.equal(r.lastErrorCode,'HUE_TIMEOUT')});
await test('Reconnect setzt sich nach Erfolg zurück',async()=>{const r=new ReconnectController({minDelayMs:1,maxDelayMs:2});r.failure({code:'HUE_TIMEOUT'});r.success();assert.equal(r.state,'connected');assert.equal(r.attempt,0);assert.equal(r.nextRetryAt,null)});
await test('Capability-Layer normalisiert Prozentwerte',async()=>{assert.deepEqual(validateCapabilities('light',{power:true,brightness:140}),{power:true,brightness:100})});
await test('Capability-Layer weist profilfremde Werte ab',async()=>{assert.throws(()=>validateCapabilities('switch',{brightness:20},{partial:true}),e=>e.code==='CAPABILITY_INVALID')});
await test('Legacy-Gerät wird ohne Datenverlust normalisiert',async()=>{const d=migrateLegacyDevice({id:'old',integration:'simulation',type:'light',name:'Alt',on:true,brightness:72});assert.equal(d.profile,'light');assert.deepEqual(d.capabilities,{power:true,brightness:72})});
await test('Adapterdaten bleiben aus öffentlicher API',async()=>{const d=migrateLegacyDevice({id:'hue-2',hueId:'2',integration:'hue',type:'light',name:'Hue',on:true,brightness:42});assert.equal(publicDevice(d).adapterData,undefined)});
await test('Registry sendet Geräteereignis',async()=>{const sim=new SimulationAdapter(),registry=new DeviceRegistry();let added=false;registry.once('device.added',()=>{added=true});registry.upsert(sim.create({profile:'switch',name:'Test'}));assert.equal(added,true)});
await test('Simulation nutzt normalisierte Capabilities',async()=>{const sim=new SimulationAdapter(),d=sim.create({profile:'blind',name:'Rollo'});assert.equal(d.capabilities.position,50);assert.deepEqual(await sim.applyCapabilities(d,{position:-10}),{position:0})});
await test('Hue-Simulation liefert normalisiertes Modell',async()=>{const {hue}=await adapter();await hue.discover();await hue.pair();const [light]=await hue.listDevices();assert.equal(light.profile,'light');assert.equal(light.capabilities.brightness,50);assert.equal(light.adapterData.hueId,'1')});
await test('Backup v2 besitzt gültige SHA-256-Prüfsumme',async()=>{const sim=new SimulationAdapter(),backup=createBackup({rooms:[{id:'room',name:'Raum'}],devices:[sim.create({profile:'switch',name:'Dose'})],onboarding:{selectedTheme:'Clear'}});assert.equal(backup.schemaVersion,2);assert.equal(backup.checksum.length,64);assert.equal(validateBackup(backup).data.devices.length,1)});
await test('Manipuliertes Backup wird abgewiesen',async()=>{const backup=createBackup({rooms:[],devices:[],onboarding:{}});backup.data.rooms.push({id:'x',name:'Manipuliert'});assert.throws(()=>validateBackup(backup),e=>e.code==='BACKUP_INVALID')});
await test('Backup v1 wird auf Schema v2 migriert',async()=>{const old={format:'systemone-backup',version:1,createdAt:new Date().toISOString(),state:{rooms:[],devices:[],onboarding:{selectedTheme:'Clear'}}};const migrated=validateBackup(old);assert.equal(migrated.schemaVersion,2);assert.equal(migrated.migrated,true)});
await test('Backup exportiert keine Hue-Geräte oder Secrets',async()=>{const sim=new SimulationAdapter(),backup=createBackup({rooms:[],devices:[sim.create({profile:'switch',name:'Dose'}),migrateLegacyDevice(demo[0])],onboarding:{selectedTheme:'Clear'},secrets:{token:'no'}});assert.equal(backup.data.devices.length,1);assert.equal(JSON.stringify(backup).includes('token'),false)});
console.log(`\n${passed}/21 Tests bestanden`);if(passed!==21)process.exitCode=1})().catch(e=>{console.error(e);process.exit(1)});
