const roomsEl=document.querySelector('#rooms');const bridgeStatusEl=document.querySelector('#bridgeStatus');const toastEl=document.querySelector('#toast');let latestState=null,liveTimer=null,pairingSession=null;
async function api(path,options={}){const r=await fetch(path,{headers:{'Content-Type':'application/json',...(options.headers||{})},...options});const p=await r.json();if(!r.ok||!p.success){const e=new Error(p?.error?.message||'Unbekannter Fehler');e.code=p?.error?.code;throw e}return p.data}
function toast(m){toastEl.textContent=m;toastEl.classList.add('show');clearTimeout(toast._timer);toast._timer=setTimeout(()=>toastEl.classList.remove('show'),3000)}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function controlHtml(d){const c=d.capabilities||{};if(d.profile==='light')return `<input class="brightness" type="range" min="0" max="100" value="${c.brightness??50}"><button class="switch ${c.power?'on':''}"></button>`;if(d.profile==='switch')return `<button class="switch ${c.power?'on':''}"></button>`;if(d.profile==='sensor')return `<strong>${esc(c.value)} ${esc(c.unit)}</strong>`;if(d.profile==='thermostat')return `<span>${esc(c.temperature)}°C</span><input class="target" type="number" min="5" max="35" step="0.5" value="${c.targetTemperature}">`;if(d.profile==='blind')return `<input class="position" type="range" min="0" max="100" value="${c.position??50}">`;return ''}
function renderRooms(state){const unassigned=state.devices.filter(d=>!state.rooms.some(r=>r.id===d.roomId));const rooms=[...state.rooms,...(unassigned.length?[{id:'__unassigned',name:'Nicht zugeordnet'}]:[])];roomsEl.innerHTML=rooms.map(room=>{const devices=room.id==='__unassigned'?unassigned:state.devices.filter(d=>d.roomId===room.id);const html=devices.length?devices.map(d=>`<div class="device ${d.online?'':'offline'}" data-device-id="${esc(d.id)}"><div class="device-main"><div class="device-heading"><div class="device-name">${esc(d.name)}</div><span class="badge ${d.online?'':'error'}">${esc(d.profile)} · ${esc(d.availability)}</span></div><div class="device-meta">${esc(d.manufacturer)} · ${esc(d.integration)} · ${esc(d.compatibility)}</div><div class="device-edit"><input class="name-input" value="${esc(d.name)}"><select class="room-select"><option value="">Raum wählen</option>${state.rooms.map(r=>`<option value="${esc(r.id)}" ${r.id===d.roomId?'selected':''}>${esc(r.name)}</option>`).join('')}</select><button class="save-device secondary">Speichern</button></div></div><div class="controls">${controlHtml(d)}</div></div>`).join(''):'<p class="muted">Noch keine Geräte in diesem Raum.</p>';return `<article class="room-card"><div class="room-top"><div><p class="eyebrow">RAUM</p><h3>${esc(room.name)}</h3></div><span class="badge">${devices.length} Geräte</span></div><div class="device-list">${html}</div></article>`}).join('');bindDevices()}
function bindDevices(){document.querySelectorAll('.device').forEach(el=>{const id=el.dataset.deviceId;const send=async patch=>{try{await api(`/api/devices/${encodeURIComponent(id)}`,{method:'PATCH',body:JSON.stringify(patch)});await refresh(false)}catch(e){toast(`${e.code||'FEHLER'}: ${e.message}`)}};el.querySelector('.switch')?.addEventListener('click',e=>send({capabilities:{power:!e.currentTarget.classList.contains('on')}}));el.querySelector('.brightness')?.addEventListener('change',e=>send({capabilities:{brightness:Number(e.target.value)}}));el.querySelector('.target')?.addEventListener('change',e=>send({capabilities:{targetTemperature:Number(e.target.value)}}));el.querySelector('.position')?.addEventListener('change',e=>send({capabilities:{position:Number(e.target.value)}}));el.querySelector('.save-device')?.addEventListener('click',()=>send({name:el.querySelector('.name-input').value.trim(),roomId:el.querySelector('.room-select').value}))})}
function renderHeader(s){const h=s.integrations.hue,rc=h.reconnect||{};bridgeStatusEl.textContent=h.mode==='simulation'?`Hue Simulation · ${rc.state||'sicher'}`:h.paired?(h.syncError?`Hue · ${rc.state||'Syncfehler'}`:'Hue verbunden'):h.discovered?'Hue Bridge gefunden':'Keine Bridge gefunden';document.querySelector('#pairHue').textContent=h.mode==='simulation'?(h.paired?'Simulation verbunden':'Simulation starten'):(h.paired?'Hue verbunden':h.discovered?'Link-Taste drücken & koppeln':'Hue suchen');document.querySelector('#pairHue').disabled=h.paired;document.querySelector('#pairAdmin').textContent=s.onboarding.adminPaired?'Admin gekoppelt':'Admin-Pairing starten';document.querySelector('#pairAdmin').disabled=s.onboarding.adminPaired}
async function renderSetup(){try{const s=await api('/api/setup');document.querySelector('#setupSteps').innerHTML=s.steps.map(step=>`<div class="setup-step ${step.done?'done':''}"><span>${step.done?'✓':'○'}</span><span>${esc(step.label)}</span></div>`).join('');document.querySelector('#setupHeadline').textContent=s.completed?'Einrichtung theoretisch abgeschlossen':'SystemONE Schritt für Schritt';document.querySelector('#setupHint').textContent=s.completed?'Alle aktuellen MVP-Prüfschritte sind erfüllt. Ein echter Hue-Hardwaretest bleibt bewusst separat.':`Nächster Schritt: ${s.steps.find(x=>!x.done)?.label||'fertig'}`;}catch(e){}}
async function renderDiagnostics(){try{const d=await api('/api/diagnostics'),r=d.reconnect||{};document.querySelector('#diagnosticStatus').textContent=`${d.health.status.toUpperCase()} · ${d.hue.mode}`;document.querySelector('#reconnectStatus').textContent=`Reconnect: ${r.state||'idle'}${r.attempt?` · Versuch ${r.attempt}`:''}${r.nextRetryAt?` · nächster Versuch ${new Date(r.nextRetryAt).toLocaleTimeString()}`:''}`;document.querySelector('#diagnosticList').innerHTML=[...d.health.recentErrors,...d.health.recentWarnings].slice(0,5).map(e=>`<li><strong>${esc(e.code)}</strong> – ${esc(e.message)}</li>`).join('')||'<li>Keine Fehler protokolliert.</li>'}catch(e){}}
function renderAutomations(state){const list=state.automations||[];document.querySelector('#automationList').innerHTML=list.length?list.map(a=>`<article class="automation-item"><div><strong>${esc(a.name)}</strong><p class="muted">${a.enabled?'Aktiv':'Pausiert'}${a.lastRun?` · zuletzt ${new Date(a.lastRun).toLocaleString()}`:''}${a.lastError?` · ${esc(a.lastError.code)}`:''}</p></div><div class="automation-actions"><button class="secondary toggle-automation" data-id="${esc(a.id)}" data-enabled="${a.enabled}">${a.enabled?'Pausieren':'Aktivieren'}</button><button class="secondary delete-automation" data-id="${esc(a.id)}">Löschen</button></div></article>`).join(''):'<p class="muted">Noch keine Automation angelegt.</p>';document.querySelectorAll('.toggle-automation').forEach(button=>button.addEventListener('click',async()=>{await api(`/api/automations/${encodeURIComponent(button.dataset.id)}`,{method:'PATCH',body:JSON.stringify({enabled:button.dataset.enabled!=='true'})});await refresh(false)}));document.querySelectorAll('.delete-automation').forEach(button=>button.addEventListener('click',async()=>{await api(`/api/automations/${encodeURIComponent(button.dataset.id)}`,{method:'DELETE'});await refresh(false)}))}
function populateAutomationDevices(state){const devices=state.devices||[],trigger=document.querySelector('#automationTrigger'),action=document.querySelector('#automationAction');const selectedTrigger=trigger.value,selectedAction=action.value;trigger.innerHTML=devices.map(d=>`<option value="${esc(d.id)}">Wenn: ${esc(d.name)} (${esc(d.profile)})</option>`).join('')||'<option value="">Zuerst Gerät anlegen</option>';action.innerHTML=devices.map(d=>`<option value="${esc(d.id)}">Dann: ${esc(d.name)} (${esc(d.profile)})</option>`).join('')||'<option value="">Zuerst Gerät anlegen</option>';if(devices.some(d=>d.id===selectedTrigger))trigger.value=selectedTrigger;if(devices.some(d=>d.id===selectedAction))action.value=selectedAction}
async function refresh(sync=true){latestState=await api(`/api/state${sync?'?sync=1':''}`);renderRooms(latestState);renderHeader(latestState);renderAutomations(latestState);populateAutomationDevices(latestState);await Promise.all([renderDiagnostics(),renderSetup()])}
document.querySelector('#pairAdmin').addEventListener('click',async()=>{try{pairingSession=await api('/api/onboarding/pair-admin/session',{method:'POST',body:'{}'});document.querySelector('#pairCode').textContent=`Code ${pairingSession.code} · gültig bis ${new Date(pairingSession.expiresAt).toLocaleTimeString()}`;document.querySelector('#pairQr').src=pairingSession.qrDataUrl;document.querySelector('#pairingPanel').hidden=false;toast('Lokaler QR-Code für das Admin-Pairing erstellt.')}catch(e){toast(e.message)}})
document.querySelector('#simulateQrScan').addEventListener('click',async()=>{if(!pairingSession)return toast('Zuerst Pairing starten');try{await api('/api/onboarding/pair-admin/complete',{method:'POST',body:JSON.stringify({token:pairingSession.token,code:pairingSession.code})});pairingSession=null;document.querySelector('#pairingPanel').hidden=true;await refresh(false);toast('QR-Scan und Admin-Pairing lokal simuliert')}catch(e){toast(`${e.code||'FEHLER'}: ${e.message}`)}})
document.querySelector('#pairHue').addEventListener('click',async()=>{try{if(!latestState.integrations.hue.discovered)await api('/api/integrations/hue/discover');await api('/api/integrations/hue/pair',{method:'POST',body:'{}'});await refresh(true);toast(latestState?.integrations?.hue?.mode==='simulation'?'Hue-Simulation gekoppelt':'Hue gekoppelt')}catch(e){toast(`${e.code||'FEHLER'}: ${e.message}`)}})
document.querySelector('#reconnectHue').addEventListener('click',async()=>{try{await api('/api/integrations/hue/reconnect',{method:'POST',body:'{}'});await refresh(false);toast('Reconnect-Zyklus manuell gestartet')}catch(e){toast(`${e.code||'FEHLER'}: ${e.message}`)}})
document.querySelector('#addRoom').addEventListener('click',async()=>{const i=document.querySelector('#newRoomName'),name=i.value.trim();if(!name)return toast('Raumname fehlt');await api('/api/rooms',{method:'POST',body:JSON.stringify({name})});i.value='';await refresh(false);await populateRooms()})
document.querySelector('#addSimDevice').addEventListener('click',async()=>{const type=document.querySelector('#deviceType').value,roomId=document.querySelector('#deviceRoom').value,name=document.querySelector('#deviceName').value.trim();try{await api('/api/devices/simulate',{method:'POST',body:JSON.stringify({type,roomId,name})});document.querySelector('#deviceName').value='';await refresh(false);toast('Simulationsgerät angelegt')}catch(e){toast(e.message)}})
document.querySelector('#addAutomation').addEventListener('click',async()=>{const body={templateId:document.querySelector('#automationTemplate').value,triggerDeviceId:document.querySelector('#automationTrigger').value,actionDeviceId:document.querySelector('#automationAction').value,threshold:Number(document.querySelector('#automationThreshold').value)};try{await api('/api/automations/from-template',{method:'POST',body:JSON.stringify(body)});await refresh(false);toast('Lokale Automation angelegt')}catch(e){toast(`${e.code||'FEHLER'}: ${e.message}`)}})
document.querySelector('#refresh').addEventListener('click',()=>refresh(true).catch(e=>toast(e.message)));document.querySelector('#diagnose').addEventListener('click',()=>renderDiagnostics().then(()=>toast('Diagnose aktualisiert')));
async function populateRooms(){const rooms=await api('/api/rooms');document.querySelector('#deviceRoom').innerHTML='<option value="">Ohne Raum</option>'+rooms.map(r=>`<option value="${esc(r.id)}">${esc(r.name)}</option>`).join('')}
refresh(false).then(populateRooms).then(()=>{liveTimer=setInterval(()=>{if(!document.hidden&&latestState?.integrations?.hue?.paired)refresh(false).catch(()=>{})},3000)}).catch(e=>toast(e.message));window.addEventListener('beforeunload',()=>clearInterval(liveTimer));
