const roomsEl=document.querySelector('#rooms');const bridgeStatusEl=document.querySelector('#bridgeStatus');const toastEl=document.querySelector('#toast');let latestState=null,liveTimer=null;
async function api(path,options={}){const r=await fetch(path,{headers:{'Content-Type':'application/json',...(options.headers||{})},...options});const p=await r.json();if(!r.ok||!p.success){const e=new Error(p?.error?.message||'Unbekannter Fehler');e.code=p?.error?.code;throw e}return p.data}
function toast(m){toastEl.textContent=m;toastEl.classList.add('show');clearTimeout(toast._timer);toast._timer=setTimeout(()=>toastEl.classList.remove('show'),3000)}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function controlHtml(d){if(d.type==='light')return `<input class="brightness" type="range" min="1" max="100" value="${d.brightness??50}"><button class="switch ${d.on?'on':''}"></button>`;if(d.type==='switch')return `<button class="switch ${d.on?'on':''}"></button>`;if(d.type==='sensor')return `<strong>${esc(d.value)} ${esc(d.unit)}</strong>`;if(d.type==='thermostat')return `<span>${esc(d.temperature)}°C</span><input class="target" type="number" min="5" max="35" step="0.5" value="${d.targetTemperature}">`;if(d.type==='blind')return `<input class="position" type="range" min="0" max="100" value="${d.position??50}">`;return ''}
function renderRooms(state){const unassigned=state.devices.filter(d=>!state.rooms.some(r=>r.id===d.roomId));const rooms=[...state.rooms,...(unassigned.length?[{id:'__unassigned',name:'Nicht zugeordnet'}]:[])];roomsEl.innerHTML=rooms.map(room=>{const devices=room.id==='__unassigned'?unassigned:state.devices.filter(d=>d.roomId===room.id);const html=devices.length?devices.map(d=>`<div class="device ${d.online?'':'offline'}" data-device-id="${esc(d.id)}"><div class="device-main"><div class="device-heading"><div class="device-name">${esc(d.name)}</div><span class="badge ${d.online?'':'error'}">${esc(d.type)} · ${d.online?'online':'offline'}</span></div><div class="device-meta">${esc(d.integration)}</div><div class="device-edit"><input class="name-input" value="${esc(d.name)}"><select class="room-select"><option value="">Raum wählen</option>${state.rooms.map(r=>`<option value="${esc(r.id)}" ${r.id===d.roomId?'selected':''}>${esc(r.name)}</option>`).join('')}</select><button class="save-device secondary">Speichern</button></div></div><div class="controls">${controlHtml(d)}</div></div>`).join(''):'<p class="muted">Noch keine Geräte in diesem Raum.</p>';return `<article class="room-card"><div class="room-top"><div><p class="eyebrow">RAUM</p><h3>${esc(room.name)}</h3></div><span class="badge">${devices.length} Geräte</span></div><div class="device-list">${html}</div></article>`}).join('');bindDevices()}
function bindDevices(){document.querySelectorAll('.device').forEach(el=>{const id=el.dataset.deviceId;const send=async patch=>{try{await api(`/api/devices/${encodeURIComponent(id)}`,{method:'PATCH',body:JSON.stringify(patch)});await refresh(false)}catch(e){toast(`${e.code||'FEHLER'}: ${e.message}`)}};el.querySelector('.switch')?.addEventListener('click',e=>send({on:!e.currentTarget.classList.contains('on')}));el.querySelector('.brightness')?.addEventListener('change',e=>send({brightness:Number(e.target.value)}));el.querySelector('.target')?.addEventListener('change',e=>send({targetTemperature:Number(e.target.value)}));el.querySelector('.position')?.addEventListener('change',e=>send({position:Number(e.target.value)}));el.querySelector('.save-device')?.addEventListener('click',()=>send({name:el.querySelector('.name-input').value.trim(),roomId:el.querySelector('.room-select').value}))})}
function renderHeader(s){const h=s.integrations.hue,rc=h.reconnect||{};bridgeStatusEl.textContent=h.mode==='simulation'?`Hue Simulation · ${rc.state||'sicher'}`:h.paired?(h.syncError?`Hue · ${rc.state||'Syncfehler'}`:'Hue verbunden'):h.discovered?'Hue Bridge gefunden':'Keine Bridge gefunden';document.querySelector('#pairHue').textContent=h.mode==='simulation'?(h.paired?'Simulation verbunden':'Simulation starten'):(h.paired?'Hue verbunden':h.discovered?'Link-Taste drücken & koppeln':'Hue suchen');document.querySelector('#pairHue').disabled=h.paired;document.querySelector('#pairAdmin').textContent=s.onboarding.adminPaired?'Admin gekoppelt':'Admin-Pairing starten';document.querySelector('#pairAdmin').disabled=s.onboarding.adminPaired}
async function renderSetup(){try{const s=await api('/api/setup');document.querySelector('#setupSteps').innerHTML=s.steps.map(step=>`<div class="setup-step ${step.done?'done':''}"><span>${step.done?'✓':'○'}</span><span>${esc(step.label)}</span></div>`).join('');document.querySelector('#setupHeadline').textContent=s.completed?'Einrichtung theoretisch abgeschlossen':'SystemONE Schritt für Schritt';document.querySelector('#setupHint').textContent=s.completed?'Alle aktuellen MVP-Prüfschritte sind erfüllt. Ein echter Hue-Hardwaretest bleibt bewusst separat.':`Nächster Schritt: ${s.steps.find(x=>!x.done)?.label||'fertig'}`;}catch(e){}}
async function renderDiagnostics(){try{const d=await api('/api/diagnostics'),r=d.reconnect||{};document.querySelector('#diagnosticStatus').textContent=`${d.health.status.toUpperCase()} · ${d.hue.mode}`;document.querySelector('#reconnectStatus').textContent=`Reconnect: ${r.state||'idle'}${r.attempt?` · Versuch ${r.attempt}`:''}${r.nextRetryAt?` · nächster Versuch ${new Date(r.nextRetryAt).toLocaleTimeString()}`:''}`;document.querySelector('#diagnosticList').innerHTML=[...d.health.recentErrors,...d.health.recentWarnings].slice(0,5).map(e=>`<li><strong>${esc(e.code)}</strong> – ${esc(e.message)}</li>`).join('')||'<li>Keine Fehler protokolliert.</li>'}catch(e){}}
async function refresh(sync=true){latestState=await api(`/api/state${sync?'?sync=1':''}`);renderRooms(latestState);renderHeader(latestState);await Promise.all([renderDiagnostics(),renderSetup()])}
document.querySelector('#pairAdmin').addEventListener('click',async()=>{try{const s=await api('/api/onboarding/pair-admin/session',{method:'POST',body:'{}'});document.querySelector('#pairCode').textContent=`Code ${s.code} · gültig bis ${new Date(s.expiresAt).toLocaleTimeString()}`;document.querySelector('#pairQr').src=s.qrDataUrl;document.querySelector('#pairingPanel').hidden=false;toast('Lokaler QR-Code für das Admin-Pairing erstellt.')}catch(e){toast(e.message)}})
document.querySelector('#pairHue').addEventListener('click',async()=>{try{if(!latestState.integrations.hue.discovered)await api('/api/integrations/hue/discover');await api('/api/integrations/hue/pair',{method:'POST',body:'{}'});await refresh(true);toast(latestState?.integrations?.hue?.mode==='simulation'?'Hue-Simulation gekoppelt':'Hue gekoppelt')}catch(e){toast(`${e.code||'FEHLER'}: ${e.message}`)}})
document.querySelector('#reconnectHue').addEventListener('click',async()=>{try{await api('/api/integrations/hue/reconnect',{method:'POST',body:'{}'});await refresh(false);toast('Reconnect-Zyklus manuell gestartet')}catch(e){toast(`${e.code||'FEHLER'}: ${e.message}`)}})
document.querySelector('#addRoom').addEventListener('click',async()=>{const i=document.querySelector('#newRoomName'),name=i.value.trim();if(!name)return toast('Raumname fehlt');await api('/api/rooms',{method:'POST',body:JSON.stringify({name})});i.value='';await refresh(false);await populateRooms()})
document.querySelector('#addSimDevice').addEventListener('click',async()=>{const type=document.querySelector('#deviceType').value,roomId=document.querySelector('#deviceRoom').value,name=document.querySelector('#deviceName').value.trim();try{await api('/api/devices/simulate',{method:'POST',body:JSON.stringify({type,roomId,name})});document.querySelector('#deviceName').value='';await refresh(false);toast('Simulationsgerät angelegt')}catch(e){toast(e.message)}})
document.querySelector('#refresh').addEventListener('click',()=>refresh(true).catch(e=>toast(e.message)));document.querySelector('#diagnose').addEventListener('click',()=>renderDiagnostics().then(()=>toast('Diagnose aktualisiert')));
async function populateRooms(){const rooms=await api('/api/rooms');document.querySelector('#deviceRoom').innerHTML='<option value="">Ohne Raum</option>'+rooms.map(r=>`<option value="${esc(r.id)}">${esc(r.name)}</option>`).join('')}
refresh(false).then(populateRooms).then(()=>{liveTimer=setInterval(()=>{if(!document.hidden&&latestState?.integrations?.hue?.paired)refresh(false).catch(()=>{})},3000)}).catch(e=>toast(e.message));window.addEventListener('beforeunload',()=>clearInterval(liveTimer));
