const crypto=require('crypto');
function slotError(code,message){return Object.assign(new Error(message),{code})}
function createSlotState(version='0.4.0'){return{schemaVersion:1,activeSlot:'A',slots:{A:{version,status:'confirmed'},B:{version:null,status:'empty'}},dataPartition:{id:'systemone-data',generation:1},pendingBoot:null,lastRollback:null,consumedApprovalIds:[],acceptedUpdates:[]}}
function publicUpdateSlotState(state){
  const slots=Object.fromEntries(Object.entries(state?.slots||{}).map(([id,slot])=>[id,{version:slot?.version||null,status:slot?.status||'unknown',...(slot?.stagedAt?{stagedAt:slot.stagedAt}:{}),...(slot?.payloadHash?{payloadFingerprint:String(slot.payloadHash).slice(0,16)}:{})}]));
  const pending=state?.pendingBoot;
  return{schemaVersion:state?.schemaVersion||1,activeSlot:state?.activeSlot||null,slots,dataPartition:{generation:Number(state?.dataPartition?.generation)||0},pendingBoot:pending?{previousSlot:pending.previousSlot,candidateSlot:pending.candidateSlot,startedAt:pending.startedAt,healthDeadline:pending.healthDeadline}:null,lastRollback:state?.lastRollback?{at:state.lastRollback.at,from:state.lastRollback.from,to:state.lastRollback.to,reason:state.lastRollback.reason}:null,replayProtection:{consumedApprovals:Array.isArray(state?.consumedApprovalIds)?state.consumedApprovalIds.length:0,acceptedPayloads:Array.isArray(state?.acceptedUpdates)?state.acceptedUpdates.length:0}};
}
function stageUpdate(state,validation,approval,now=new Date()){if(!validation?.valid||!approval?.approvalId||approval.singleUse!==true||approval.version!==validation.version||approval.payloadHash!==validation.payloadHash)throw slotError('UPDATE_APPROVAL_INVALID','Geprüftes Update und einmalige Adminfreigabe passen nicht zusammen.');const consumed=state.consumedApprovalIds||[],accepted=state.acceptedUpdates||[];if(consumed.includes(approval.approvalId))throw slotError('UPDATE_APPROVAL_REPLAY','Diese Adminfreigabe wurde bereits verwendet.');if(accepted.some(item=>item.payloadHash===validation.payloadHash))throw slotError('UPDATE_PAYLOAD_REPLAY','Dieses signierte Updatepaket wurde bereits angenommen.');if(state.pendingBoot)throw slotError('UPDATE_CYCLE_ACTIVE','Ein Update wartet bereits auf den Boot-Healthcheck.');const next=structuredClone(state),target=state.activeSlot==='A'?'B':'A';if(['staged','candidate'].includes(state.slots?.[target]?.status))throw slotError('UPDATE_SLOT_BUSY','Der inaktive Slot enthält bereits ein laufendes Update.');const stagedAt=now.toISOString();next.slots[target]={version:validation.version,status:'staged',payloadHash:validation.payloadHash,approvalId:approval.approvalId,stagedAt};next.consumedApprovalIds=[...consumed,approval.approvalId].slice(-100);next.acceptedUpdates=[...accepted,{version:validation.version,payloadHash:validation.payloadHash,approvalId:approval.approvalId,acceptedAt:stagedAt}].slice(-100);return{state:next,targetSlot:target}}
function activateStaged(state,targetSlot,now=new Date()){const target=state.slots?.[targetSlot];if(!target||target.status!=='staged')throw slotError('UPDATE_SLOT_INVALID','Inaktiver Slot enthält kein geprüftes Update.');const next=structuredClone(state),previous=next.activeSlot;next.activeSlot=targetSlot;next.slots[targetSlot].status='candidate';next.pendingBoot={id:`boot-${crypto.randomBytes(6).toString('hex')}`,previousSlot:previous,candidateSlot:targetSlot,startedAt:now.toISOString(),healthDeadline:new Date(now.getTime()+5*60000).toISOString(),dataGeneration:next.dataPartition.generation};return next}
function rollback(state,reason,now=new Date()){if(!state.pendingBoot)return structuredClone(state);const next=structuredClone(state),pending=next.pendingBoot;next.activeSlot=pending.previousSlot;next.slots[pending.previousSlot].status='confirmed';next.slots[pending.candidateSlot].status='failed';next.lastRollback={at:now.toISOString(),from:pending.candidateSlot,to:pending.previousSlot,reason};next.pendingBoot=null;return next}
function reportBootHealth(state,{healthy,migrationsOk},now=new Date()){if(!state.pendingBoot)throw slotError('UPDATE_BOOT_MISSING','Kein ausstehender Update-Boot vorhanden.');if(!healthy)return rollback(state,'health-check-failed',now);if(!migrationsOk)return rollback(state,'migration-failed',now);const next=structuredClone(state),candidate=next.pendingBoot.candidateSlot;next.slots[candidate].status='confirmed';next.pendingBoot=null;return next}
function recoverInterruptedBoot(state,now=new Date()){return state.pendingBoot?rollback(state,'power-loss-or-unconfirmed-boot',now):structuredClone(state)}
module.exports={createSlotState,publicUpdateSlotState,stageUpdate,activateStaged,reportBootHealth,recoverInterruptedBoot,rollback}
