const crypto=require('crypto');
function updateError(code,message){return Object.assign(new Error(message),{code})}
function canonical(value){if(Array.isArray(value))return`[${value.map(canonical).join(',')}]`;if(value&&typeof value==='object')return`{${Object.keys(value).sort().map(key=>`${JSON.stringify(key)}:${canonical(value[key])}`).join(',')}}`;return JSON.stringify(value)}
function versionParts(value){if(!/^\d+\.\d+\.\d+$/.test(String(value||'')))throw updateError('UPDATE_VERSION_INVALID','Updateversion muss SemVer im Format X.Y.Z sein.');return String(value).split('.').map(Number)}
function compareVersions(a,b){const left=versionParts(a),right=versionParts(b);for(let i=0;i<3;i++)if(left[i]!==right[i])return left[i]>right[i]?1:-1;return 0}
function signingInput(manifest,payloadHash){return Buffer.from(`${canonical(manifest)}\n${payloadHash}`)}
function createUpdatePackage({manifest,payload,privateKey}){const bytes=Buffer.isBuffer(payload)?payload:Buffer.from(payload),payloadHash=crypto.createHash('sha256').update(bytes).digest('hex'),normalized={schemaVersion:1,target:manifest.target,version:manifest.version,minCoreVersion:manifest.minCoreVersion,kind:manifest.kind||'functional',createdAt:manifest.createdAt||new Date().toISOString(),notes:String(manifest.notes||'').slice(0,500)};return{format:'systemone-update',manifest:normalized,payload:bytes.toString('base64'),payloadHash,signature:crypto.sign(null,signingInput(normalized,payloadHash),privateKey).toString('base64')}}
function validateUpdatePackage(input,{publicKey,currentVersion,target='systemone-pi'}={}){if(!publicKey)throw updateError('UPDATE_TRUST_MISSING','Vertrauensschlüssel für Updates fehlt.');if(input?.format!=='systemone-update'||input?.manifest?.schemaVersion!==1)throw updateError('UPDATE_FORMAT_INVALID','Updateformat oder Schemaversion ist ungültig.');const bytes=Buffer.from(String(input.payload||''),'base64'),hash=crypto.createHash('sha256').update(bytes).digest('hex');if(hash!==input.payloadHash)throw updateError('UPDATE_PAYLOAD_TAMPERED','Updateinhalt stimmt nicht mit dem signierten Hash überein.');if(!crypto.verify(null,signingInput(input.manifest,input.payloadHash),publicKey,Buffer.from(String(input.signature||''),'base64')))throw updateError('UPDATE_SIGNATURE_INVALID','Updatesignatur ist ungültig.');if(input.manifest.target!==target)throw updateError('UPDATE_INCOMPATIBLE','Update ist nicht für SystemONE Pi bestimmt.');if(compareVersions(input.manifest.version,currentVersion)<=0)throw updateError('UPDATE_VERSION_INVALID','Updateversion muss höher als die installierte Version sein.');if(compareVersions(currentVersion,input.manifest.minCoreVersion)<0)throw updateError('UPDATE_INCOMPATIBLE','Installierte Core-Version erfüllt die Mindestversion nicht.');return{valid:true,format:input.format,version:input.manifest.version,currentVersion,target,kind:input.manifest.kind,notes:input.manifest.notes,payloadHash:input.payloadHash,requiresAdminApproval:input.manifest.kind==='functional'}}
function approveUpdate(validation,actor,now=new Date()){if(!validation?.valid||!actor?.id||!['owner','administrator'].includes(actor.role))throw updateError('UPDATE_APPROVAL_REQUIRED','Funktionales Update benötigt eine lokale Adminfreigabe.');return{approvalId:`update-approval-${crypto.randomBytes(8).toString('hex')}`,version:validation.version,payloadHash:validation.payloadHash,approvedAt:now.toISOString(),approvedBy:{id:actor.id,role:actor.role},singleUse:true}}
module.exports={canonical,compareVersions,createUpdatePackage,validateUpdatePackage,approveUpdate}
