"""audit chain

Revision ID: 0003
Revises: 0002
Create Date: 2026-08-18 10:56:55.650797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_events', sa.Column('sequence_number', sa.Integer(), nullable=False))
    op.add_column('audit_events', sa.Column('previous_hash', sa.String(length=64), nullable=False))
    op.add_column('audit_events', sa.Column('record_hash', sa.String(length=64), nullable=False))
    op.create_unique_constraint('uq_audit_events_sequence_number', 'audit_events', ['sequence_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_audit_events_sequence_number', 'audit_events', type_='unique')
    op.drop_column('audit_events', 'record_hash')
    op.drop_column('audit_events', 'previous_hash')
    op.drop_column('audit_events', 'sequence_number')
    # ### end Alembic commands ###
