"""room import mapping

Revision ID: 0004
Revises: 0003
Create Date: 2026-08-18 17:51:27.399459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('integration_id', sa.UUID(), nullable=True))
    op.add_column('rooms', sa.Column('external_id', sa.String(length=300), nullable=True))
    op.create_index('uq_rooms_integration_external_id', 'rooms', ['integration_id', 'external_id'], unique=True, postgresql_where=sa.text('external_id IS NOT NULL'))
    op.create_foreign_key('fk_rooms_integration_id_integrations', 'rooms', 'integrations', ['integration_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_rooms_integration_id_integrations', 'rooms', type_='foreignkey')
    op.drop_index('uq_rooms_integration_external_id', table_name='rooms', postgresql_where=sa.text('external_id IS NOT NULL'))
    op.drop_column('rooms', 'external_id')
    op.drop_column('rooms', 'integration_id')
    # ### end Alembic commands ###
